CLASS_NAMES = [
    "No Finding",
    "Enlarged Cardiomediastinum",
    "Cardiomegaly",
    "Lung Opacity",
    "Lung Lesion",
    "Edema",
    "Consolidation",
    "Pneumonia",
    "Atelectasis",
    "Pneumothorax",
    "Pleural Effusion",
    "Pleural Other",
    "Fracture",
    "Support Devices",
]
DIAGNOSIS_EXPLANATIONS = {
    "No Finding": "No clear abnormalities detected.",
    "Cardiomegaly": "The heart appears larger than normal.",
    "Enlarged Cardiomediastinum": "The central chest structures look wider than usual.",
    "Lung Opacity": "An area of the lung looks denser than expected.",
    "Lung Lesion": "A suspicious area in the lung that may need further evaluation.",
    "Edema": "Possible fluid buildup in the lungs.",
    "Consolidation": "Lung tissue may be filled with fluid or infection.",
    "Pneumonia": "Findings may be consistent with lung infection.",
    "Atelectasis": "Part of the lung may be partially collapsed.",
    "Pneumothorax": "Possible air leak causing lung collapse.",
    "Pleural Effusion": "Fluid may be present around the lung.",
    "Pleural Other": "Other abnormalities in the pleural space.",
    "Fracture": "Possible bone injury detected.",
    "Support Devices": "Medical devices (e.g. tubes, lines) are visible.",
}
